import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_KR } from "next/font/google";
import Image from "next/image";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const notoSansKr = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin", "latin-ext"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="Ij37Fo71XLQ_7jIt4HEnRKeRYveFfyMUwhVnrVgXMNI"
        />
        <meta
          name="naver-site-verification"
          content="78620915d4073b38f73f28eb83c6722017bc62b9"
        />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-X6S68TMWZJ"
          strategy="afterInteractive"
        />
        <Script id="ga4" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-X6S68TMWZJ');
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSansKr.variable} bg-gray-50 antialiased`}
      >
        <header className="sticky top-0 right-0 left-0 z-50 mx-auto h-15 max-w-150 bg-white py-2">
          <Image
            src="/logo.svg"
            alt="Datwe"
            width={100}
            height={44}
            className="mx-auto"
          />
        </header>

        <main className="mx-auto max-w-150 bg-white">{children}</main>
        <footer className="bg-background mx-auto max-w-150 py-10">
          <p className="text-center text-sm text-gray-500">
            조건 추가 문의 :{" "}
            <a href="mailto:devssc93@gmail.com">devssc93@gmail.com</a>
          </p>
        </footer>
      </body>
    </html>
  );
}
